# Generated by Django 6.0.5 on 2026-05-19 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowing',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='borrowing',
            old_name='user_id',
            new_name='user',
        ),
    ]
