from django.urls import path, include
from rest_framework.routers import DefaultRouter
from borrowings.views import BorrowingViewSet

# Create a router and register our ViewSet
router = DefaultRouter()
router.register("borrowings", BorrowingViewSet, basename="borrowing")

app_name = "borrowings"

urlpatterns = [
    # Include all the URLs automatically generated by the router
    path("", include(router.urls)),
]